home: Home
categories: Categories
uncategorized: Uncategorized
untitled: Untitled
updated: Updated at
archive: Archives
tags: Tags
links: Friends
recent_posts: Recent posts
recent_comments: Recent comments
days_ago: days ago
search: Input keyword
no_tags: No tags set
prev_post: Previous post
next_post: Next post
navigation: Navigation
to_top: Back to top
no_match: No matched content
page_non_exist: The content you request does not exist!
jump_back_home: Will jump back %2$s in %1$s
author: Author
posted_at: Posted at
updated_at: Updated at
license: Licensed under
comment_in: Comment in %s
views: Views
