home: 主页
categories: 分类
uncategorized: 未分类
untitled: 未命名
updated: 更新时间
archive: 归档
tags: 标签
links: 友情链接
recent_posts: 最近更新的文章
recent_comments: 最近评论
days_ago: 天前
search: 输入关键词
no_tags: 未设置标签
prev_post: 上一篇文章
next_post: 下一篇文章
navigation: 导航
to_top: 送你上天
\,: ，
\:: ：
no_match: 搜索未能找到匹配结果
page_non_exist: 您所要访问的页面不存在！
jump_back_home: 将在%s后跳回%s
seconds: 秒
author: 作者
posted_at: 发布日期
updated_at: 修改日期
license: 发布协议
comment_in: 于 %s 的评论
views: 次点击
