keywords:

since:

logo: 

favicon: false

nav:
  - title: 归档
    url: archives/
    icon: fa-archive
    description:
  - title: 关于
    url: about/
    icon: fa-user
    description:

# notice:
#   - "**Notice** one"
#   - "~~Notice~~ two"

# Register at https://disqus.com/api/applications to get disqus_api_key
# Use the API Key, not the API Secret
disqus_shortname:
disqus_api_key:

search: true

busuanzi: true

tag_number: 25
full_content: false

# Provided colors: red, green, blue, purple
color_theme: blue

# Available: katex | mathjax
math: mathjax

# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero | copyright
# Any other words are valid but do not have a special style
license: copyright

toc:
  collapse: false

sns:
  github: wolfhong
  twitter:
  facebook:
  linkedin:
  googleplus_id:
  steam_id:
  weibo:
  zhihu:
  tieba:

buttons:
  base: true
  border: false
  borderless: false
  raised: false
  3d: false
  glowing: false
  dropdown: false
  group: false
  wrapper: false
  shadow: false

links:
  - title: "Felix's Blog"
    url: https://blog.felixc.at/
    description: 一个大神
